version: "3.8"

services:
  frontend:
    build: ./finance-dashboard
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./finance-dashboard:/app:cached
      - /app/node_modules

  backend:
    build: ./finance-backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/finance_db
    volumes:
      - ./finance-backend:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user", "-d", "finance_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
